name: ftt
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - babel=2.17.0
  - backports.zstd=1.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - docutils=0.22.3
  - double-conversion=3.4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagesize=1.4.1
  - jinja2=3.1.6
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - llvmlite=0.46.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mkl=2025.3.0
  - munkres=1.1.4
  - numba=0.63.1
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.14.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.10.1
  - requests=2.32.5
  - roman-numerals=4.0.0
  - six=1.17.0
  - snowballstemmer=3.0.1
  - sphinx=9.0.4
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - tbb=2022.3.0
  - tk=8.6.13
  - tornado=6.5.4
  - tqdm=4.67.1
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - urllib3=2.6.2
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - bottle==0.13.4
      - click==8.3.1
      - fastapi==0.124.4
      - h11==0.16.0
      - line-profiler==5.0.0
      - paste==3.10.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - setuptools==80.9.0
      - starlette==0.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
prefix: C:\Users\Work\anaconda3\envs\ftt
