[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "future-technology-transformation"
version = "1.0.0"
description = "FTT Standalone model"
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["SourceCode"]
